services:
  load-test:
    image: grafana/k6:latest
    depends_on:
      - datadog-agent
    environment:
      - K6_STATSD_ENABLE_TAGS=true
      - K6_STATSD_ADDR=172.17.0.1:8125

  datadog-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_SITE=datadoghq.com
      - DD_API_KEY=<SENSITIVE_DATA>
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
    ports:
      - "8125:8125/udp"